# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# The UUID for the Trusted Application
BINARY=0e35e2c9-b329-4ad9-a2f5-8ca9bbbd7713

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
