# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.

snd-soc-tegra-utils-oot-objs		:= tegra_asoc_utils.o tegra_asoc_machine.o \
					   tegra_isomgr_bw.o tegra_codecs.o
snd-soc-tegra210-ahub-oot-objs		:= tegra210_ahub.o
snd-soc-tegra210-dmic-oot-objs		:= tegra210_dmic.o
snd-soc-tegra210-i2s-oot-objs		:= tegra210_i2s.o
snd-soc-tegra186-dspk-oot-objs		:= tegra186_dspk.o
snd-soc-tegra210-admaif-oot-objs	:= tegra210_admaif.o
snd-soc-tegra210-amx-oot-objs		:= tegra210_amx.o
snd-soc-tegra210-adx-oot-objs		:= tegra210_adx.o
snd-soc-tegra210-mixer-oot-objs		:= tegra210_mixer.o
snd-soc-tegra210-sfc-oot-objs		:= tegra210_sfc.o
snd-soc-tegra210-afc-oot-objs		:= tegra210_afc.o
snd-soc-tegra210-mvc-oot-objs		:= tegra210_mvc.o
snd-soc-tegra210-iqc-oot-objs		:= tegra210_iqc.o
snd-soc-tegra186-asrc-oot-objs		:= tegra186_asrc.o
snd-soc-tegra186-arad-oot-objs		:= tegra186_arad.o
snd-soc-tegra210-ope-oot-objs		:= tegra210_ope.o tegra210_peq.o \
					   tegra210_mbdrc.o
snd-soc-tegra-machine-driver-oot-objs	:= tegra_machine_driver.o
snd-soc-tegra-controls-objs		:= tegra_mixer_control.o

obj-m += snd-soc-tegra-utils-oot.o
obj-m += snd-soc-tegra210-dmic-oot.o
obj-m += snd-soc-tegra210-ahub-oot.o
obj-m += snd-soc-tegra210-i2s-oot.o
obj-m += snd-soc-tegra186-dspk-oot.o
obj-m += snd-soc-tegra210-admaif-oot.o
obj-m += snd-soc-tegra210-amx-oot.o
obj-m += snd-soc-tegra210-adx-oot.o
obj-m += snd-soc-tegra210-mixer-oot.o
obj-m += snd-soc-tegra210-sfc-oot.o
obj-m += snd-soc-tegra210-afc-oot.o
obj-m += snd-soc-tegra210-mvc-oot.o
obj-m += snd-soc-tegra210-iqc-oot.o
obj-m += snd-soc-tegra210-ope-oot.o
obj-m += snd-soc-tegra186-arad-oot.o
obj-m += snd-soc-tegra186-asrc-oot.o
obj-m += snd-soc-tegra-machine-driver-oot.o
obj-m += snd-soc-tegra-controls.o
