# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION. All rights reserved.

snd-soc-tegra-utils-oot-objs		:= tegra_asoc_utils.o tegra_asoc_machine.o \
					   tegra_isomgr_bw.o tegra_codecs.o
snd-soc-tegra210-afc-oot-objs		:= tegra210_afc.o
snd-soc-tegra210-iqc-oot-objs		:= tegra210_iqc.o
snd-soc-tegra186-arad-oot-objs		:= tegra186_arad.o
snd-soc-tegra-machine-driver-oot-objs	:= tegra_machine_driver.o
snd-soc-tegra-controls-objs		:= tegra_mixer_control.o

obj-m += snd-soc-tegra-utils-oot.o
obj-m += snd-soc-tegra210-afc-oot.o
obj-m += snd-soc-tegra210-iqc-oot.o
obj-m += snd-soc-tegra186-arad-oot.o
obj-m += snd-soc-tegra-machine-driver-oot.o
obj-m += snd-soc-tegra-controls.o
