# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright 2022 Maxim Integrated
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# gpio support: vendor provided GPL-2.0 licensed MFD gpio driver

obj-m += gpio-max77851.o

