variables:
  CONFIG: ""
  BOARDID: ""
  BOARDSKU: ""
  FAB: ""
  BOARDREV: ""
  CHIP_SKU: ""
  IS_CUSTOM: "0" #disable custom image build by default
  START_TASK: ""
  INSTALL_NV_JP: "1" #enable install nvidia-jetpack by default
  BUILD_QSPI_IMG: "1" #enable image build for qspi flash by default
  JETPACKVER: "6.2.1"
  JETSONVER: "38.4.0"
  ROOTFS_NAME: "Tegra_Linux_Sample-Root-Filesystem_r38.4.0_aarch64.tbz2"
  UPDATE_DRV_DEPEND: "1"
  KCFLAGS: ""

stages:
  - jetson-agx-thor-devkit
  - recomputer-thor-carrier-j601
  - custom-firmware

# common code of building target image
.build_image: &build_image_script
  - > 
    if [ -z "$CONFIG" ]; then echo "Error: CONFIG variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - > 
    if [ -z "$BOARDID" ]; then echo "Error: BOARDID variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - > 
    if [ -z "$BOARDSKU" ]; then echo "Error: BOARDSKU variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - > 
    if [ -z "$FAB" ]; then echo "Error: FAB variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - > 
    if [ -z "$BOARDREV" ]; then echo "Error: BOARDREV variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - > 
    if [ -z "$CHIP_SKU" ]; then echo "Error: CHIP_SKU variable is empty, Please setup it before enable this CI!"; exit 1; fi
  - echo "config details, CONFIG $CONFIG,BOARDID $BOARDID,BOARDSKU $BOARDSKU,FAB $FAB,BOARDREV $BOARDREV,CHIP_SKU $CHIP_SKU,INSTALL_NV_JP $INSTALL_NV_JP"
  - git submodule sync
  - git submodule update --init --recursive
  - id 
  - export DATE_STR=$(TZ='Asia/Hong_Kong' date +%Y-%m-%d)
  # clean the rootfs for every image
  - mkdir -p rootfs
  - rm -rf rootfs/*
  - wget  http://192.168.1.77/jetson/$ROOTFS_NAME -q
  - tar xpf $ROOTFS_NAME -C rootfs
  # this is special for jetson orin nano 4g
  - >
    if [[ $BOARDID == "3767" && $BOARDSKU == "0004" ]]; then
      cp -v extra_scripts/chip_info.bin_bak bootloader/chip_info.bin_bak
    fi
  # apply necessary changes to rootfs
  # if BOARDID is 3834, then apply openrm
  - >
    if [[ $BOARDID == "3834" ]]; then
      ./apply_binaries.sh --openrm
    else
      ./apply_binaries.sh
    fi
  # record the system image name and commit info of seeed to target rootfs.
  - echo "# Seeed Image Name mfi_$CI_JOB_STAGE-$JETPACKVER-$JETSONVER-$DATE_STR.tar.gz" >> ./rootfs/etc/nv_tegra_release
  - echo "# branch $CI_COMMIT_REF_NAME" >> ./rootfs/etc/nv_tegra_release
  - echo "# commit ID $CI_COMMIT_SHA" >> ./rootfs/etc/nv_tegra_release
  # reconfigure the kernel log level
  - >
    if [ -f rootfs/etc/sysctl.conf ]; then
      sed -i '/^kernel\.printk/s/^/#/' rootfs/etc/sysctl.conf
      echo "kernel.printk = 5 6 1 7" >> rootfs/etc/sysctl.conf
    fi
  # prepare the compile toolchains
  - wget  http://192.168.1.77/jetson/aarch64--glibc--stable-2022.08-1.tar.bz2 -q
  - mkdir -p l4t-gcc
  - tar xf aarch64--glibc--stable-2022.08-1.tar.bz2 -C ./l4t-gcc
  - export ARCH=arm64
  - export CROSS_COMPILE=`realpath .`/l4t-gcc/aarch64--glibc--stable-2022.08-1/bin/aarch64-buildroot-linux-gnu-
  # build the kernel
  - cd source/
  - ln -sf ../../../../../../nvethernetrm nvidia-oot/drivers/net/ethernet/nvidia/nvethernet/nvethernetrm
  - ./nvbuild.sh
  # deploy new kernel and dtb
  - ./do_copy.sh
  # deploy camera overlay dtbo to rootfs
  - cp ../kernel/dtb/tegra264-p4071-camera-* ../rootfs/boot/
  # deploy new kernel drviers
  - export INSTALL_MOD_PATH=`realpath ../rootfs/`
  - ./nvbuild.sh -i
  - cd ..
  # update initrd
  - ./tools/l4t_update_initrd.sh
  - >
    if [ $BUILD_QSPI_IMG == "1" ]; then
      # package the image for qspi flash (Thor uses internal NVMe/UFS storage)
      sudo BOARDID=$BOARDID BOARDSKU=$BOARDSKU FAB=$FAB BOARDREV=$BOARDREV CHIP_SKU=$CHIP_SKU ./tools/kernel_flash/l4t_initrd_flash.sh --qspi-only --no-flash --massflash 5 --network usb0 $CONFIG external
      md5sum mfi_$CONFIG.tar.gz > chksum-$CI_JOB_STAGE-qspiflash-$DATE_STR.txt
      sha256sum mfi_$CONFIG.tar.gz >> chksum-$CI_JOB_STAGE-qspiflash-$DATE_STR.txt
      # upload image of qspi
      mkdir -p deploy
      mount -t cifs -o username=$SMB_USER,password=$SMB_PWD,vers=3.0,uid=`id -u`,gid=`id -g`,rw,file_mode=0664 //192.168.1.77/red_2t/jetson deploy
      cp mfi_$CONFIG.tar.gz deploy/mfi_$CI_JOB_STAGE-qspiflash-$JETPACKVER-$JETSONVER-$DATE_STR.tar.gz || true
      cp chksum-$CI_JOB_STAGE-qspiflash-$DATE_STR.txt deploy/ || true
      umount deploy
    fi
  # install user custom package(optional)
  - sed -i "s/<SOC>/t264/g" rootfs/etc/apt/sources.list.d/nvidia-l4t-apt-source.list
  - sudo sed -i 's|^ExecStart=/usr/lib/bluetooth/bluetoothd -d --noplugin=audio,a2dp,avrcp$|ExecStart=/usr/lib/bluetooth/bluetoothd -d|' rootfs/lib/systemd/system/bluetooth.service.d/nv-bluetooth-service.conf
  - mount --bind /sys ./rootfs/sys
  - mount --bind /dev ./rootfs/dev
  - mount --bind /dev/pts ./rootfs/dev/pts
  - mount --bind /proc ./rootfs/proc
  - cp /usr/bin/qemu-aarch64-static rootfs/usr/bin/
  - cp extra_scripts/rootfs_magic.sh rootfs
  - >
    if [ $INSTALL_NV_JP == "1" ]; then
      chroot rootfs /rootfs_magic.sh || true
    fi
  #update kernel module dependencies
  - KER_NUM=`basename $(find ./rootfs/lib/modules -mindepth 1 -maxdepth 1 -type d)`
  - >
    if [ $UPDATE_DRV_DEPEND == "1" ]; then
      echo "current kernel number $KER_NUM"
      sudo chroot rootfs depmod -a  $KER_NUM
    fi
  - umount ./rootfs/sys
  - umount ./rootfs/dev/pts
  - umount ./rootfs/dev
  - umount ./rootfs/proc
  - rm rootfs/rootfs_magic.sh
  - rm rootfs/usr/bin/qemu-aarch64-static
  # package the image for qspi & nvme flash
  - sudo BOARDID=$BOARDID BOARDSKU=$BOARDSKU FAB=$FAB BOARDREV=$BOARDREV CHIP_SKU=$CHIP_SKU ./tools/kernel_flash/l4t_initrd_flash.sh --external-device nvme0n1p1 -c tools/kernel_flash/flash_l4t_t264_nvme.xml -S 80GiB -p "-c bootloader/flash_l4t_t264_qspi.xml --no-systemimg" --no-flash --massflash 5 --network usb0 $CONFIG external
  - md5sum mfi_$CONFIG.tar.gz > chksum-$CI_JOB_STAGE-$DATE_STR.txt
  - sha256sum mfi_$CONFIG.tar.gz >> chksum-$CI_JOB_STAGE-$DATE_STR.txt
  # upload image of qspi & nvme ssd
  - mkdir -p deploy
  - mount -t cifs -o username=$SMB_USER,password=$SMB_PWD,vers=3.0,uid=`id -u`,gid=`id -g`,rw,file_mode=0664 //192.168.1.77/red_2t/jetson deploy 
  - cp mfi_$CONFIG.tar.gz deploy/mfi_$CI_JOB_STAGE-$JETPACKVER-$JETSONVER-$DATE_STR.tar.gz || true
  - cp chksum-$CI_JOB_STAGE-$DATE_STR.txt deploy/ || true
  - umount deploy

jetson-agx-thor-devkit:
  stage: jetson-agx-thor-devkit
  timeout: 3h
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - if: '$START_TASK == "jetson-agx-thor-devkit"'
      when: on_success
    - if: '$START_TASK == $CI_JOB_STAGE'
      when: on_success
  tags:
    - x86-shell
  variables:
    CONFIG: "jetson-agx-thor-devkit"
    BOARDID: "3834"
    BOARDSKU: "0008"
    FAB: "400"
    BOARDREV: "G.5"
    CHIP_SKU: "00:00:00:A0"

  script:
    - echo "Building for $CONFIG"
    - *build_image_script

recomputer-thor-carrier-j601:
  stage: recomputer-thor-carrier-j601
  timeout: 3h
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - if: '$START_TASK == "recomputer-thor-carrier-j601"'
      when: on_success
    - if: '$START_TASK == $CI_JOB_STAGE'
      when: on_success
  tags:
    - x86-shell
  variables:
    CONFIG: "recomputer-thor-carrier-j601"
    BOARDID: "3834"
    BOARDSKU: "0008"
    FAB: "400"
    BOARDREV: "G.5"
    CHIP_SKU: "00:00:00:A0"

  script:
    - echo "Building for $CONFIG"
    - *build_image_script

build-custom-firmware:
   stage: custom-firmware
   rules:
     - if: '$IS_CUSTOM == "1"'
       when: on_success 
     - if: '$CI_COMMIT_TAG'
       when: never 
   tags:
     - x86-shell

   script:
    - echo "Building custom image for $CONFIG"
    - *build_image_script
