# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Seeed Technology Inc.
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Sourced by bash script.
# Disable unused variable check. Most of these variables are used in an outer
# script that sources this file.

source "${LDK_DIR}/p3737-0000-p3701-0000.conf";

update_flash_args_p3737_0000_p3701_0000()
{
	# Select the Base DTB based on SKU
	if [ "${board_sku}" = "0000" ]; then
		if [[ "${board_FAB}" != "QS"* && "${board_FAB}" != "TS"* ]]; then
			# Enable VRS11 DCM mode for CPU/GPU/CV rails
			PMIC_CONFIG="tegra234-mb1-bct-pmic-p3701-0005.dts";
		fi
		DTB_FILE=tegra234-p3737-0000+p3701-0000-seeed.dtb;
	elif [ "${board_sku}" = "0001" ] || [ "${board_sku}" = "0002" ]; then
		DTB_FILE=tegra234-p3737-0000+p3701-0000-seeed.dtb;
	elif [ "${board_sku}" = "0004" ]; then
		# Enable VRS11 DCM mode for CPU/GPU/CV rails
		PMIC_CONFIG="tegra234-mb1-bct-pmic-p3701-0005.dts";
		DTB_FILE=tegra234-p3737-0000+p3701-0004-seeed.dtb;
	elif [ "${board_sku}" = "0005" ]; then
		# Enable VRS11 DCM mode for CPU/GPU/CV rails
		PMIC_CONFIG="tegra234-mb1-bct-pmic-p3701-0005.dts";
		DTB_FILE=tegra234-p3737-0000+p3701-0005-seeed.dtb;
	else
		echo "Error: Unrecognized module SKU ${board_sku}";
		exit 1;
	fi

	TBCDTB_FILE="${DTB_FILE}";
}

PINMUX_CONFIG="seeed-agx-orin-kit-mb1-bct-pinmux-p3701-0000.dtsi";
PMC_CONFIG="seeed-agx-orin-kit-mb1-bct-padvoltage-p3701-0000.dtsi";
DTB_FILE=tegra234-p3737-0000+p3701-0000-seeed.dtb;
TBCDTB_FILE="${DTB_FILE}";
