# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifdef CONFIG_MEDIA_SUPPORT
obj-m += cdi/
obj-m += tpg/
endif
obj-m += isc/
obj-m += camera/
obj-m += cam_fsync/
