# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

nvtzvault-objs += nvtzvault-main.o oesp-mailbox.o nvtzvault-helper.o
nvtzvault-y += nvtzvault-main.o
obj-m += nvtzvault.o
