# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifndef CONFIG_TEGRA_SYSTEM_TYPE_ACK
ifneq ($(NV_OOT_REALTEK_RTL8822CE_SKIP_BUILD),y)
obj-m += rtl8822ce/
endif

ifneq ($(NV_OOT_REALTEK_RTL8852CE_SKIP_BUILD),y)
obj-m += rtl8852ce/
endif
endif
