# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2024, NVIDIA CORPORATION.  All rights reserved.

ifdef CONFIG_PCIE_TEGRA194_EP
obj-m += pci-epf-dma-test.o
obj-m += pci-epf-tegra-dma-sanity.o
obj-m += pci-epf-tegra-vnet.o
endif
