# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.

ifdef CONFIG_PCIE_TEGRA194_EP
obj-m += pci-epf-dma-test.o
ifdef CONFIG_TEGRA_HOST1X
obj-m += pci-epf-tegra-vnet.o
endif
endif
