# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.

ifndef CONFIG_TEGRA_SYSTEM_TYPE_ACK
obj-m   += tegra_wmark.o
endif
obj-m   += governor_pod_scaling.o
