# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

ifdef CONFIG_I2C
obj-m += drm/tegra/
obj-m += host1x/
obj-m += host1x-fence/
obj-m += host1x-nvhost/
endif
