# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.
#
# Tegra Host1x-Nvhost Driver.

ccflags-y += -DCONFIG_TEGRA_HOST1X
ccflags-y += -Werror

host1x-nvhost-objs = nvhost.o

obj-m += host1x-nvhost.o
