#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Usage: ./host_flash_qspi.sh
# This script flashes the Tegra from host through the tegra's usb device interface
# using the images generated by tools/qspi_flash/generate_qspi_for_flash.sh

set -e

function show_usage() {
	echo "Usage: ${0} [-b, --boardctl] [-h, --help]"
cat <<EOF
	By default, user must manually put the board into recovery mode and reset it after flashing is complete..
	Otherwise, Specify --boardctl to use bsp boardctl to put the tegra in recovery mode and reset it after flashing.
	Options:
	-b, --boardctl  Use bsp boardctl to put the tegra in recovery mode and reset it after flashing
	-h, --help  Show this help message
EOF
}

if [ "$(id -u)" -ne 0 ]; then
	echo "Error: This script requires root privilege."
	exit 1
fi

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
	case $1 in
		-b|--boardctl) USE_BSP_BOARDCTL=true ;;
		-h|--help) show_usage; exit 0 ;;
		*) echo "Unknown parameter passed: ${1}"; show_usage; exit 1 ;;
	esac
	shift
done

RCMBOOT_CMD_FILE="rcmbootcmd.txt"
QSPI_FLASH_DIR="hostflash"
QSPI_FLASH_LOG="qspi_flash.log"
# Default to not using BSP boardctl
USE_BSP_BOARDCTL="${USE_BSP_BOARDCTL:-false}"
if [ "${USE_BSP_BOARDCTL}" = true ]; then
	# Use bsp boardctl to put the tegra in recovery mode
	./tools/board_automation/boardctl -t topo recovery
fi

#
# Flash the QSPI flash
#
pushd "./${QSPI_FLASH_DIR}" > /dev/null || exit 1
bash "./${RCMBOOT_CMD_FILE}" | tee "${QSPI_FLASH_LOG}"
if [ ! -s "${QSPI_FLASH_LOG}" ]; then
	echo "Please put the board in recovery mode"
	exit 1
fi
echo "Waiting for 6 minutes before reboot the tegra......."
sleep 360

popd > /dev/null || exit 1

if [ "${USE_BSP_BOARDCTL}" = true ]; then
	./tools/board_automation/boardctl -t topo reset
fi
