[pytest]
addopts = -v --strict --cov-branch --cov-report=term-missing --cache-clear
markers =
    targetneeded: this test needs a target to execute
    hostonly: this test only needs a host machine to execute
    manual: this test needs manual interaction with tester
    devel: this test is currently in development
    debug: this is so that a single test can be run in debug
    unitTest: run unit tests
    createbsp: this will run all create_bsp_images tests
    flashbsp: this will run all flash_bsp_images tests
    bootburn: Runs full bootburn runs (time intensive)
    firmware: this will run the tests of FW flashing in bootbun_firmware
    yaml: Tests for the yaml_config.py
    aurix: Tests for the aurix, target required
    flashutils: Shell utilities wrapper tests
    parser: Test the command line parser
    targetConfig: Test the target configuration class
    platform: Test PDK platform options
    trace:  Tests with -T option
    asym: Runs asymmetric boot chain tests
    ucd: Run update customer data unit tests
