#!/usr/bin/python
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

import os
import sys
from flashtools_nverror import nverror
from target_config import target_config
from bootburn_lib import bootburn_lib
from bootburn_adb import partitionInformation
from bootburn_adb import bootburn_adb
from flash_utilities import shell_utilities
from bootburn_parser import commandline_parser

import argparse

class ResignBsp(object):

    input_options = {
        "-h": (0, "Display help", False),  # BoardName
        "-c": (1, "chip ID example: 0x19", True),
        "-i": (1, "Input path containing already signed images.", True),
        "-o": (1, "Output directory path.", True),
        "-p": (1, "Provide private key file for SBK signing.", False),
        "-e": (1, "Provide encryption key file", False),
        "-D": (0, "Debug mode", False),
        "--internal": (0, "Internal ToT repository.  Defaults to PDK")
    }

    HdrType = {"BrBct": 8, "BCH": 9, "internal": 0}

    debugging = False
    bootburnLib = bootburn_lib
    targetConfig = target_config
    shellUtils = shell_utilities()
    f_PkcFile = None
    s_PkcArg = ""
    f_EncryptFile = None
    s_EkcArg = ""
    p_InDirPath = None
    p_OutDirPath = None
    parser = None
    parsed_commandline = []
    nvresign = None
    chipID = "0x19"

    def __init__(self, bootburnLib):
        self.bootburnLib = bootburnLib
        self.targetConfig = bootburnLib.targetConfig
        self.shellUtils.setMonitor(targetConfig.sysMonitor)
        self.parser = argparse.ArgumentParser(description="Parser", add_help=False)
        for option, arg in self.input_options.items():
            numArguments = arg[0]
            helpMessage = arg[1]
            if numArguments > 0:
                self.parser.add_argument(option, help=helpMessage, nargs=numArguments)
            elif numArguments == False:
                self.parser.add_argument(option, help=helpMessage, action="store_true")
            else:
                self.parser.add_argument(option, help=helpMessage, nargs="+")

        self.nvresign = self.targetConfig.flashUtils.f_NvResign
        self.parsed_commandline = self.parser.parse_args(sys.argv[1:])
        self.parsed_commandline = vars(self.parsed_commandline)
        if(self.parsed_commandline and self.parsed_commandline["D"]):
            self.debugging = True

    def log(self, msg, verbose=False):
        if(verbose or self.debugging):
            print(msg)

    def vlog(self, msg):
        self.log(msg, True)

    def ReSignHelp(self):

        self.vlog("\nUsage")
        self.vlog("<args>")
        self.vlog("-h    : Display help")
        self.vlog("-i    : Input path containing already signed images.")
        self.vlog(
            "      : This layout must be same as output generated by running create_bsp_images.sh.")
        self.vlog("-o    : Output directory path.")
        self.vlog("-c    : Chip ID")
        self.vlog("-p    : Provide private key file for SBK signing.")
        self.vlog("-e    : Provide Encryption key file.\n")

    def ErrorCondition(self, errorCode):

        if(errorCode != 0):
            self.vlog("Error in execution. Error Code " + str(errorCode) + ". Exiting")
            sys.exit(errorCode)
        else:
            self.vlog("Exception thrown. Exiting")
            sys.exit(-1)

    def GetParams(self):
        for option in self.parsed_commandline:
            argument = self.parsed_commandline[option]

            if(option == "h" and argument == True):
                self.ReSignHelp()
                sys.exit(0)
            elif(option == "c" and argument != None):
                self.chipID = argument[0]
            elif(option == "i" and argument != None):
                self.p_InDirPath = argument[0]
            elif(option == "o" and argument != None):
                self.p_OutDirPath = argument[0]
            elif(option == "p" and argument != None):
                self.f_PkcFile = argument[0]
                self.s_PkcArg=" --pkc " + argument[0]
            elif(option == "e" and argument != None):
                self.s_EkcArg = " --ekc " + argument[0]
                self.f_EncryptFile = argument[0]
            elif (option == "D" and argument != None):
                self.debugging = argument;

    def ValidateParams(self, p_InDirPath):
        if(self.p_OutDirPath == None):
            self.vlog("Error: Output path with argument -g is missing.")
            self.ErrorCondition(-1)

        if(self.p_InDirPath and os.path.isdir(self.p_InDirPath) == False):
            self.vlog("Error: Input path (with argument -i) is invalid.")
            self.ErrorCondition(-1)

        if(self.p_OutDirPath and os.path.isdir(self.p_OutDirPath) == False):
            self.shellUtils.makeDirectory(self.p_OutDirPath)

        # if(self.p_InDirPath == self.p_OutDirPath):
        #     self.shellUtils.makeDirectory(self.p_OutDirPath)
        #     self.vlog("Output path cannot be same as input path")
        #     self.ErrorCondition(-1)

        # if(-self.f_PkcFile == None and self.f_EncryptFile == None):
        #     self.vlog(
        #         "Error: private key or Encryption file must be specified with -p or -e argument")
        #     self.ErrorCondition(-1)

    def readFileToFlash(self, path):
        adbObj = bootburn_adb(self.targetConfig, self.targetConfig.flashUtils)
        # l_FilesToFlashTxt=`find p_InColdBootPath - iname "*FileToFlash*"`
        l_FilesToFlashTxt = self.shellUtils.find(path, "FileToFlash.txt")
        if(len(l_FilesToFlashTxt) == 0 or len(l_FilesToFlashTxt) > 1):
            self.vlog("Could not find unique FileToFlash.txt - " +
                      str(l_FilesToFlashTxt))
            self.ErrorCondition(-1)

        inputPath = os.path.dirname(l_FilesToFlashTxt[0])
        fid = open(l_FilesToFlashTxt[0], "r")
        manifest = fid.read()
        fid.close()

        partitions = []
        for partition in manifest.splitlines():
            partition = partition.strip()
            if(partition[0] == "#"):
                continue

            partition = partition.split("#")[0]
            partitionInfo = adbObj.parseFileToFlashEntry(partition)
            partitionInfo.FileName = os.path.join(inputPath, partitionInfo.FileName)
            partitions += [partitionInfo]

        return partitions

    # Move text files containing flashing info to new path and change the names
    # as required
    def CopyTargetInfo(self, targetInfoPath, outputPath):
        targetInfo = self.shellUtils.catFile(targetInfoPath)
        targetInfo = targetInfo.replace('SecureTarget=False', 'SecureTarget=True')
        fid = open(os.path.join(outputPath, 'TargetInfo.txt'), 'w')
        fid.write(targetInfo)
        fid.close()

    def executeNvResign(self, image, headerType, outputDir):
        resignCommand = self.nvresign
        resignCommand += " --chip " + self.chipID
        resignCommand += " --image " + image
        resignCommand += " --headertype " + str(headerType) + self.s_PkcArg + self.s_EkcArg
        resignCommand += " --outpath " + outputDir
        if(self.debugging):
            self.vlog(resignCommand)
        self.shellUtils.executeShellCommand(resignCommand, self.debugging, self.debugging)

    def executeNvResignRcmPartName(self, l_File, Partname_RcmMsg, l_OutputPath):
        resignCommand = self.nvresign
        resignCommand  = " --chip " + self.chipID
        resignCommand += " --image " + l_File
        resignCommand += " --partname " + Partname_RcmMsg
        resignCommand += self.s_PkcArg + self.s_EkcArg + " --outpath " + l_OutputPath
        if(self.debugging):
            self.vlog(resignCommand)
        self.shellUtils.executeShellCommand(resignCommand, self.debugging, self.debugging)

    def ReSignColdBootImages(self, inputPath, outputPath):
        if(os.path.isfile(os.path.join(inputPath, 'FileToFlash.txt')) == False):
            self.vlog("Could not find FileToFlash.txt in " + inputPath)
            return False

        self.shellUtils.makeDirectory(outputPath)
        self.bootburnLib.CopyTegraSign(outputPath)
        cwd = os.getcwd()
        os.chdir(outputPath)

        self.vlog("Re-signing images for cold-boot")
        partitions = self.readFileToFlash(inputPath)
        for p in partitions:
            if(int(p.ImageHeaderType) == self.HdrType["BrBct"]):
                self.vlog("\tRe-sign: " + p.PartitionName)
                self.executeNvResign(p.FileName, p.ImageHeaderType, outputPath)
                # Sign the B chain BCT also
                fileName = p.FileName.replace("A_", "B_")
                self.executeNvResign(fileName, p.ImageHeaderType, outputPath)

            elif(int(p.ImageHeaderType) == self.HdrType["BCH"]):
                fid = open(p.FileName, "r")
                header = fid.read(4)
                fid.close()
                if(header == "NVDA"):
                    self.vlog("\tRe-sign: " + p.FileName)
                    self.executeNvResign(p.FileName, p.ImageHeaderType, outputPath)
                else:
                    # This image does not have a BCH header; it might be grouped with other binary.
                    # So, copy the image to the output dir and change the name
                    self.vlog("\tCopy (grouped binary): " + p.PartitionName)
                    basename = os.path.basename(p.FileName)
                    basename = basename.replace("_zerosign", "_signed")
                    self.shellUtils.Copy(p.FileName, os.path.join(outputPath, basename))
            else:
                self.vlog("\tCopy: " + p.FileName)
                # Just copy the image to the output dir
                self.shellUtils.Copy(p.FileName, outputPath)
        self.shellUtils.Copy(os.path.join(inputPath, 'FileToFlash.txt'), outputPath)
        os.chdir(cwd)

    def ReSignRcmMessages(self, l_InputPath, l_OutputPath):

        l_RcmFiles = []
        s_Partname_RcmMsg="rcm-message"

        self.shellUtils.makeDirectory(l_OutputPath)
        self.bootburnLib.CopyTegraSign(l_OutputPath)
        # Re-sign RCM messages.
        self.vlog("\tRe-sign: RCM messages `basename l_OutputPath")
        for f in os.listdir(l_InputPath):
            fileExtension = os.path.splitext(f)[1]
            if(os.path.isfile(f) == True and fileExtension == ".rcm"):
                l_RcmFiles += [l_InputPath + "/" + f]

        for l_SingleRcmFile in l_RcmFiles:
            basename = os.path.basename(l_SingleRcmFile)
            basename = basename.replace("_encrypt.rcm", ".rcm")
            self.shellUtils.Copy(l_SingleRcmFile, os.path.join(l_OutputPath, basename))
            self.vlog("\tRe-sign: RCM message `basename l_File")
            self.executeNvResignRcmPartName(l_SingleRcmFile, s_Partname_RcmMsg, l_OutputPath)

        if(os.path.isfile(os.path.join(l_InputPath, "rcm_list.xml"))):
            inRcmList = os.path.join(l_InputPath, "rcm_list.xml")
            self.shellUtils.CopyifSrcisafile(inRcmList, l_OutputPath)
        else:
            inRcmList = os.path.join(l_InputPath, "rcm_list_signed.xml")
            outRcmList = os.path.join(l_OutputPath, "rcm_list.xml")
            self.shellUtils.CopyifSrcisafile(inRcmList, outRcmList)

        cwd = os.getcwd()
        os.chdir(l_OutputPath)

        tegrasignCommand  = "./tegrasign_v2 -key " + self.f_PkcFile
        tegrasignCommand += " --list rcm_list.xml"
        tegrasignCommand += " --pubkeyhash pubkey.bin"
        tegrasignCommand += " --getmontgomeryvalues mont.bin"

        self.vlog(tegrasignCommand)
        self.shellUtils.executeShellCommand(tegrasignCommand, False, True)

        tegraRcmCommand  = "./tegrarcm_v2 --chip " + self.chipID
        tegraRcmCommand += " --updatesig rcm_list_signed.xml"
        tegraRcmCommand += " --pubkeyhash pubkey.bin"
        tegraRcmCommand += " --setmontgomeryvalues mont.bin"
        self.shellUtils.executeShellCommand(tegraRcmCommand, False, True)
        os.chdir(cwd)

    def ReSignRcmImages(self, l_InputPath, l_OutputPath):
        l_BrBct="bct_BR"
        s_Partname_Rcm="rcm-message"

        self.shellUtils.makeDirectory(l_OutputPath)
        self.bootburnLib.CopyTegraSign(l_OutputPath)
        cwd = os.getcwd()
        os.chdir(l_OutputPath)

        filesToSign = []
        blobFiles = []
        appletFiles = []
        self.vlog("Re-signing RCM images at `basename l_InputPath")
        for f in os.listdir(l_InputPath):
            f = l_InputPath + "/" + f
            if(os.path.isfile(f) == True and f.find("zerosign") != -1):
                filesToSign += [f]
            elif(os.path.isfile(f) == True and f == "rcm_blob.bin"):
                blobFiles += [f]

        for f in os.listdir(os.path.join(l_InputPath, "applet")):
            f = l_InputPath + "/" + f
            if(os.path.isfile(f) == True and f == "applet_blob.bin"):
                blobFiles += [f]

        for l_File in filesToSign:
            if ( l_File.find(l_BrBct) != -1):
                l_HdrType=self.HdrType["BrBct"]
            else:
                l_HdrType=self.HdrType["BCH"]

            self.vlog("\tRe-sign: " + l_File)
            self.executeNvResign(l_File, l_HdrType, l_OutputPath)

        self.vlog("\tRe-sign: RCM all blobs")
        for blob in blobFiles:
            self.executeNvResignRcmPartName(blob, s_Partname_Rcm, l_OutputPath)

        for applet in appletFiles:
            self.executeNvResign(applet, self.HdrType["BCH"], os.path.join(l_OutputPath, "applet"))

        self.ReSignRcmMessages(l_InputPath, l_OutputPath)
        self.ReSignRcmMessages(os.path.join(l_InputPath,"applet"), os.path.join(l_OutputPath, "applet"))
        os.chdir(cwd)

    def ReSignImages(self, inputPath, outputPath):
        flashImages = None
        rcmBootImages = None
        rcmFlashImages = None
        targetInfo = None

        for root, dirs, files in os.walk(inputPath):
            if('flash-images' in dirs):
                flashImages = os.path.join(root, 'flash-images')
            if('rcm-flash' in dirs):
                rcmFlashImages = os.path.join(root, 'rcm-flash')
            if('rcm-boot' in dirs):
                rcmBootImages = os.path.join(root, 'rcm-boot')
            if("TargetInfo.txt" in files):
                targetInfo = os.path.join(root, 'TargetInfo.txt')

        if(flashImages != None):
            self.ReSignColdBootImages(flashImages, os.path.join(outputPath, 'flash-images'))

        if(rcmFlashImages != None):
            self.ReSignRcmImages(rcmFlashImages, os.path.join(outputPath, 'rcm-flash'))

        if(rcmBootImages != None):
            self.ReSignRcmImages(rcmBootImages, os.path.join(outputPath, 'rcm-boot'))

        if(targetInfo != None):
            self.CopyTargetInfo(targetInfo, outputPath)

        self.vlog("Done")
        os.chdir(cwd)

if __name__ == "__main__":
    ###### Execution begins from here ######
    # if("--internal" in sys.argv):
    #     isPdkPackage = False
    # else:
    #     isPdkPackage = True
    isPdkPackage = False

    DirBeingRunFrom = os.path.realpath(__file__)
    DirBeingRunFrom = os.path.dirname(DirBeingRunFrom)
    targetConfig = target_config(isPdkPackage)

    #Dummy parser to initialize target config
    cmdParser = commandline_parser(["resign", "-b", "e3550b01-t194a"])
    cmdParser.initializeTargetConfig(targetConfig, ['b'], False)
    bootburnLib = bootburn_lib(targetConfig)

    resignObj = ResignBsp(bootburnLib)
    resignObj.GetParams()
    resignObj.ValidateParams(resignObj.p_InDirPath)

    cwd = os.getcwd()
    os.chdir(resignObj.p_OutDirPath)
    inputPath = resignObj.p_InDirPath
    outputPath = resignObj.p_OutDirPath
    resignObj.ReSignImages(inputPath, outputPath)
    os.chdir(cwd)

