# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += mc-t26x.o
obj-m += tegra264-mc-hwpm.o
obj-m += smmu-hwpm.o
obj-m += mem-qual.o
