# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifeq ($(CONFIG_MFD_CORE),y)
obj-m += nvidia-vrs-pseq.o
obj-m += max77851.o
endif
