# SPDX-License-Identifier: GPL-2.0
max_serdes_all-objs := max_ser.o max_des.o max_serdes.o

obj-m += max_serdes_all.o
obj-m += max_aggregator.o
obj-m += max96717.o
obj-m += max96724.o
obj-m += max9296a.o
