# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifneq ($(NV_OOT_REALTEK_R8168_SKIP_BUILD),y)
obj-m += r8168/
endif

ifneq ($(NV_OOT_REALTEK_R8126_SKIP_BUILD),y)
obj-m += r8126/
endif
