# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

# NOTE: Do not change or add anything in this makefile.
# The source code and makefile rules are copied from the subdirectory
# drivers/clink of nvidia-grace folder. This file is just place-holder
# for empty makefile to avoid any build issue when copy is not done
# from command line and building the tree independent of source copy.
