# Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# The UUID for the hwkey-agent TA
BINARY=82154947-c1bc-4bdf-b89d-04f93c0ea97c

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
