# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifdef CONFIG_I2C
obj-m += f75308.o

ifdef CONFIG_TEGRA_SYSTEM_TYPE_ACK
obj-m += ina232.o
endif

endif
