# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

snd-soc-tegra-utils-objs		:= tegra_asoc_machine.o \
					   tegra_isomgr_bw.o
snd-soc-tegra210-afc-objs		:= tegra210_afc.o
snd-soc-tegra210-iqc-objs		:= tegra210_iqc.o
snd-soc-tegra186-arad-objs		:= tegra186_arad.o
snd-soc-tegra210-adsp-objs		:= tegra210_adsp.o
snd-soc-tegra-controls-objs		:= tegra_mixer_control.o

obj-m += snd-soc-tegra-utils.o
obj-m += snd-soc-tegra210-afc.o
obj-m += snd-soc-tegra210-iqc.o
obj-m += snd-soc-tegra186-arad.o
obj-m += snd-soc-tegra210-adsp.o
obj-m += snd-soc-tegra-controls.o
