# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifdef CONFIG_I2C
obj-m += nvvrs-pseq-rtc.o
endif
obj-m += rtc-max77851.o
