# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

ifndef CONFIG_TEGRA_SYSTEM_TYPE_ACK
ifeq ($(VERSION).$(PATCHLEVEL),5.15)
obj-m += rtl8822ce/
endif
endif
