/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * SPDX-FileCopyrightText: Copyright (c) 2012-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */

#ifndef __UAPI_TEGRA_CEC_H
#define __UAPI_TEGRA_CEC_H

#define TEGRA_CEC_IOC_MAGIC 'C'

#define TEGRA_CEC_IOCTL_ERROR_RECOVERY		_IO(TEGRA_CEC_IOC_MAGIC, 1)
#define TEGRA_CEC_IOCTL_DUMP_REGISTERS		_IO(TEGRA_CEC_IOC_MAGIC, 2)
#define TEGRA_CEC_IOCTL_SET_RX_SNOOP		_IO(TEGRA_CEC_IOC_MAGIC, 3)
#define TEGRA_CEC_IOCTL_GET_RX_SNOOP		_IO(TEGRA_CEC_IOC_MAGIC, 4)
#define TEGRA_CEC_IOCTL_GET_POST_RECOVERY	_IO(TEGRA_CEC_IOC_MAGIC, 5)

#endif /* __UAPI_TEGRA_CEC_H */
