# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
GCOV_PROFILE := y
ccflags-y += -Werror

tegra-mce-y += tegra23x-mce.o mce.o

obj-m += tegra-mce.o
