# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
ccflags-y += -Werror

tegra-bootloader-debug-objs := tegra_bootloader_debug.o tegra_bootloader_debug_gr.o
obj-m += tegra-bootloader-debug.o
