#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2019-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

reboot_system()
{
	echo "Rebooting system..." > /dev/kmsg;
	reboot;
}

echo "Starting L4T initial RAM disk" > /dev/kmsg;

# create reboot command based on busybox
if [ ! -e "/sbin/reboot" ]; then
	echo -e "#!/bin/bash \nbusybox reboot -f" > /sbin/reboot;
	chmod 755 /sbin/reboot;
fi;

#Mount procfs, devfs, sysfs and debugfs
if ! mount -t proc proc /proc; then
	echo "ERROR: mounting proc fail..." > /dev/kmsg;
	reboot_system;
fi;
if ! mount -t devtmpfs none /dev; then
	echo "ERROR: mounting dev fail..." > /dev/kmsg;
	reboot_system;
fi;
if ! mount -t sysfs sysfs /sys; then
	echo "ERROR: mounting sys fail..." > /dev/kmsg;
	reboot_system;
fi;
if ! mount -t debugfs none /sys/kernel/debug/; then
	echo "ERROR: mounting debugfs fail..." > /dev/kmsg;
	reboot_system;
fi;

# Enter recovery kernel if matching "root=/dev/initrd" in /proc/cmdline
# Otherwise, reboot the system directly
dev_regex='root=\/dev\/initrd'
rootdev="$(grep -oE "${dev_regex}" < /proc/cmdline | tail -1)"
if [ "${rootdev}" != "" ]; then
	echo "Root device found: ${rootdev}" > /dev/kmsg;
	modprobe -v r8168;
	modprobe -v r8126;
	echo "Mount initrd as rootfs and enter recovery mode" > /dev/kmsg;
	exec /bin/bash /bin/nv_recovery.sh;
else
	reboot_system;
fi
