# SPDX-FileCopyrightText: Copyright (c) 2021-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# This file contains several "<name>=<value>" lines for customization
# in applying image-based OTA.

# Rootfs updater for updating rootfs partition
# The default value is NVIDIA provided rootfs updater. It can be set
# to customer provided rootfs updater.
ROOTFS_UPDATER="nv_ota_rootfs_updater.sh"

# Ethernet connectivity requirement
# If this option is set to "true", image-based OTA is possible only if
# the devices are connected through an Ethernet network. If it finds no
# connection, it attempts to establish one by rebooting.
# By default, this option is set to "false" since devices may not use
# ethernet as primary connectivity.
REQUIRE_ETHERNET="false"

# OTA logs
# If this option is set to "true", the logs are stored into the
# PRESERVED_OTA_LOGS_DIR directory under "/" after OTA finishes successfully.
# By default, this option is set to "false" and the OTA logs are deleted
# after OTA finishes successfully.
PRESERVE_LOGS="false"
PRESERVED_OTA_LOGS_DIR="last_ota_update_log"

# L4T Launcher
# If this option is set to "false", that means the L4T Launcher is not
# used, so skip updating the "BOOTAA64.efi" in the ESP partition.
# By default, this option is set to "true" and the "BOOTAA64.efi" in
# the ESP partition is to be updated during OTA.
USE_L4T_LAUNCHER="true"

# OTA tasks
# The tasks listed here will be executed in order in recovery kernel.
OTA_TASKS=(
	nv_ota_validate.sh
	nv_ota_update.sh
)

# The files listed here are needed to be packaged into the OTA package
# for OTA tasks.
OTA_TASK_NEEDED_FILES=(
	nv_ota_common_utils.func
	nv_ota_update_rootfs_in_recovery.sh
)
