/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/* SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */

#ifndef BPMP_ABI_MACH_T264_THERMAL_H
#define BPMP_ABI_MACH_T264_THERMAL_H

/**
 * @file
 * @defgroup bpmp_thermal_ids Thermal Zone ID's
 * @{
 */

#define TEGRA264_THERMAL_ZONE_TJ_MAX		0U
#define TEGRA264_THERMAL_ZONE_TJ_MIN		1U
#define TEGRA264_THERMAL_ZONE_GPU_AVG		2U
#define TEGRA264_THERMAL_ZONE_CPU_AVG		3U
#define TEGRA264_THERMAL_ZONE_SOC_012_AVG	4U /* Powered by Vdd_SoC */
#define TEGRA264_THERMAL_ZONE_SOC_45_AVG	5U /* Powered by Vdd_MSS */
#define TEGRA264_THERMAL_ZONE_SOC_3_AVG		6U /* Powered by Uphy_Vdd */
#define TEGRA264_THERMAL_ZONE_GPU_MAX		7U
#define TEGRA264_THERMAL_ZONE_CPU_MAX		8U
#define TEGRA264_THERMAL_ZONE_SOC_012_MAX	9U /* Powered by Vdd_SoC */
#define TEGRA264_THERMAL_ZONE_SOC_345_MAX	10U /* Powered by Uphy_Vdd and Vdd_MSS */
#define TEGRA264_THERMAL_ZONE_TJ_AVG		11U

#define TEGRA264_THERMAL_ZONE_COUNT		12U

/** @} */

/* Deprecated */

#define TEGRA264_THERMAL_ZONE_SECURE0		0U
#define TEGRA264_THERMAL_ZONE_SECURE1		1U
#define TEGRA264_THERMAL_ZONE_SECURE2		2U
#define TEGRA264_THERMAL_ZONE_SECURE3		3U
#define TEGRA264_THERMAL_ZONE_SECURE4		4U
#define TEGRA264_THERMAL_ZONE_SECURE5		5U
#define TEGRA264_THERMAL_ZONE_GENERAL0		6U
#define TEGRA264_THERMAL_ZONE_GENERAL1		7U
#define TEGRA264_THERMAL_ZONE_GENERAL2		8U
#define TEGRA264_THERMAL_ZONE_GENERAL3		9U
#define TEGRA264_THERMAL_ZONE_GENERAL4		10U
#define TEGRA264_THERMAL_ZONE_GENERAL5		11U

#endif /* BPMP_ABI_MACH_T264_THERMAL_H */
