# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

subdir-ccflags-y += -Werror

obj-m += nv_imx185.o
obj-m += nv_imx274.o
obj-m += nv_imx318.o
obj-m += nv_ov5693.o
