# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += softdog-platform.o
obj-m += watchdog-tegra-t18x.o
obj-m += max77851_wdt.o
