# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

ifeq ($(findstring ack_src,$(NV_BUILD_KERNEL_OPTIONS)),)
obj-m += pex9749-thermal.o
obj-m += tegra234-oc-event.o
obj-m += thermal-trip-event.o
endif
obj-m += max77851_thermal.o
