// SPDX-License-Identifier: GPL-2.0-only
// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

#include "pva_api_dma.h"
#include "pva_kmd.h"
#include "pva_kmd_pfsd.h"

static struct pva_dma_static_binding pfsd_dma_slot_buffers_t26x[8] = {
	 //in1
	 [0] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //in2
	 [1] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //in3
	 [2] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //hist_short_a followed by hist_int_a
	 [3] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //hist_short_b followed by hist_int_b
	 [4] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //hist_short_c followed by hist_int_c
	 [5] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //dlut_tbl_buf
	 [6] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
	 //dlut_indices_buf
	 [7] = {
		 .type = (uint8_t)PVA_DMA_STATIC_BINDING_DRAM,
	 },
 };

static struct pva_dma_descriptor pfsd_dma_descs_t26x[95] = {
	 [0] = {
		  .src = {
			  .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			  .line_pitch = 64,
			  .slot = 0 | PVA_DMA_STATIC_SLOT,
		  },
		  .dst = {
			  .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			  .line_pitch = 64,
			  .offset = 0xc0U,
		  },
		  .link_desc_id = 0,
		  .tx = 64,
		  .ty = 32,
		  .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ1,
		  .desc_reload_enable = 1,
		  .trigger_completion = 1,
	  },
	  [1] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 1 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40000U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 32,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ2,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [2] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 2 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80000U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 32,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ3,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [3] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 3 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xb5c0U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 32,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ1,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [4] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 4 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x4b500U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 32,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ2,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [5] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 5 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8b500U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 32,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ3,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [6] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 0 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93000000U,
			 .adv1 = 55552,
		 },
		 .link_desc_id = 11,
		 .tx = 64,
		 .ty = 868,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [7] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 1 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93100000U,
			 .adv1 = 55552,
		 },
		 .link_desc_id = 12,
		 .tx = 64,
		 .ty = 868,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [8] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 2 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93200000U,
			 .adv1 = 55552,
		 },
		 .link_desc_id = 13,
		 .tx = 64,
		 .ty = 868,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [9] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
			 .rpt1 = 2,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 3 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95000000U,
			 .adv1 = 57600,
			 .rpt1 = 2,
		 },
		 .link_desc_id = 14,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [10] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
			 .rpt1 = 2,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 4 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95100000U,
			 .adv1 = 57600,
			 .rpt1 = 2,
		 },
		 .link_desc_id = 15,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [11] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
			 .rpt1 = 2,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 5 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95200000U,
			 .adv1 = 57600,
			 .rpt1 = 2,
		 },
		 .link_desc_id = 16,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [12] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 6 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93300000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 17,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [13] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 7 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93400000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 18,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [14] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 8 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93500000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 19,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [15] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 9 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93600000U,
			 .adv1 = 54720,
		 },
		 .link_desc_id = 20,
		 .tx = 64,
		 .ty = 855,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [16] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 10 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93700000U,
			 .adv1 = 54720,
		 },
		 .link_desc_id = 21,
		 .tx = 64,
		 .ty = 855,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [17] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 11 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93800000U,
			 .adv1 = 54720,
		 },
		 .link_desc_id = 22,
		 .tx = 64,
		 .ty = 855,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [18] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 12 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93900000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 23,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [19] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 13 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93a00000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 24,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [20] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 14 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93b00000U,
			 .adv1 = 57600,
		 },
		 .link_desc_id = 25,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [21] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 15 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93c00000U,
			 .adv1 = 56448,
		 },
		 .link_desc_id = 26,
		 .tx = 64,
		 .ty = 882,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [22] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 16 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93d00000U,
			 .adv1 = 56448,
		 },
		 .link_desc_id = 27,
		 .tx = 64,
		 .ty = 882,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [23] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 17 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x93e00000U,
			 .adv1 = 56448,
		 },
		 .link_desc_id = 28,
		 .tx = 64,
		 .ty = 882,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [24] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 18 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94000000U,
			 .adv1 = 94208,
		 },
		 .link_desc_id = 29,
		 .tx = 64,
		 .ty = 1472,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [25] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 19 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94100000U,
			 .adv1 = 94208,
		 },
		 .link_desc_id = 30,
		 .tx = 64,
		 .ty = 1472,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [26] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 20 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94200000U,
			 .adv1 = 94208,
		 },
		 .link_desc_id = 31,
		 .tx = 64,
		 .ty = 1472,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [27] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 21 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94300000U,
			 .adv1 = 76032,
		 },
		 .link_desc_id = 32,
		 .tx = 64,
		 .ty = 1188,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [28] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 22 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94400000U,
			 .adv1 = 76032,
		 },
		 .link_desc_id = 33,
		 .tx = 64,
		 .ty = 1188,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [29] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 23 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x94500000U,
			 .adv1 = 76032,
		 },
		 .link_desc_id = 34,
		 .tx = 64,
		 .ty = 1188,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [30] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 24 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95300000U,
			 .adv1 = 83712,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 35,
		 .tx = 64,
		 .ty = 1308,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [31] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 25 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95400000U,
			 .adv1 = 83712,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 36,
		 .tx = 64,
		 .ty = 1308,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [32] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 26 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95500000U,
			 .adv1 = 83712,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 37,
		 .tx = 64,
		 .ty = 1308,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [33] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 27 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95320000U,
			 .adv1 = 122112,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 38,
		 .tx = 64,
		 .ty = 1908,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [34] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 28 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95420000U,
			 .adv1 = 122112,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 39,
		 .tx = 64,
		 .ty = 1908,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [35] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 29 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95520000U,
			 .adv1 = 122112,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 40,
		 .tx = 64,
		 .ty = 1908,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [36] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 30 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95340000U,
			 .adv1 = 110592,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 41,
		 .tx = 64,
		 .ty = 1728,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [37] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 31 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95440000U,
			 .adv1 = 110592,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 42,
		 .tx = 64,
		 .ty = 1728,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [38] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 32 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95540000U,
			 .adv1 = 110592,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 43,
		 .tx = 64,
		 .ty = 1728,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [39] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 33 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95360000U,
			 .adv1 = 54784,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 44,
		 .tx = 64,
		 .ty = 856,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [40] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 34 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95460000U,
			 .adv1 = 54784,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 48,
		 .tx = 64,
		 .ty = 856,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [41] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 35 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95560000U,
			 .adv1 = 54784,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 49,
		 .tx = 64,
		 .ty = 856,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [42] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 36 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95600000U,
			 .adv1 = 39296,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 47,
		 .tx = 64,
		 .ty = 614,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [43] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 6 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1221,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ4,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [44] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 7 | PVA_DMA_STATIC_SLOT,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1280,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		 .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_READ5,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [45] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 37 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95900000U,
			 .adv1 = 121280,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 56,
		 .tx = 64,
		 .ty = 1895,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [46] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 38 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95a00000U,
			 .adv1 = 121280,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 57,
		 .tx = 64,
		 .ty = 1895,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [47] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 39 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95b00000U,
			 .adv1 = 121280,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 58,
		 .tx = 64,
		 .ty = 1895,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [48] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 40 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95c00000U,
			 .adv1 = 98304,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1536,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [49] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 41 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95d00000U,
			 .adv1 = 98304,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1536,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [50] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 42 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95e00000U,
			 .adv1 = 98304,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1536,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [54] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 43 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x95f00000U,
			 .adv1 = 108032,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 59,
		 .tx = 64,
		 .ty = 1688,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [55] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 44 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96000000U,
			 .adv1 = 108032,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 60,
		 .tx = 64,
		 .ty = 1688,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [56] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 45 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96100000U,
			 .adv1 = 108032,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 65,
		 .tx = 64,
		 .ty = 1688,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [57] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 46 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96200000U,
			 .adv1 = 88960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 82,
		 .tx = 64,
		 .ty = 1390,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [58] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 47 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96300000U,
			 .adv1 = 88960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 83,
		 .tx = 64,
		 .ty = 1390,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [63] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 48 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96400000U,
			 .adv1 = 88960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 84,
		 .tx = 64,
		 .ty = 1390,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [64] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 49 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97000000U,
			 .adv1 = 55552,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 67,
		 .tx = 64,
		 .ty = 868,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [65] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
			 .rpt1 = 2,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 50 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97100000U,
			 .adv1 = 57600,
			 .rpt1 = 2,
		 },
		 .link_desc_id = 68,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [66] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 51 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97200000U,
			 .adv1 = 57600,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 69,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [67] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 52 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97300000U,
			 .adv1 = 54720,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 70,
		 .tx = 64,
		 .ty = 855,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [68] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 53 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97400000U,
			 .adv1 = 57600,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 71,
		 .tx = 64,
		 .ty = 900,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [69] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 54 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97500000U,
			 .adv1 = 56448,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 72,
		 .tx = 64,
		 .ty = 882,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [70] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 55 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97600000U,
			 .adv1 = 94208,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 73,
		 .tx = 64,
		 .ty = 1472,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [71] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 56 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97700000U,
			 .adv1 = 76032,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 74,
		 .tx = 64,
		 .ty = 1188,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [72] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 57 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97800000U,
			 .adv1 = 83712,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 75,
		 .tx = 64,
		 .ty = 1308,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [73] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 58 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97900000U,
			 .adv1 = 122112,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 76,
		 .tx = 64,
		 .ty = 1908,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [74] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 59 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97a00000U,
			 .adv1 = 110592,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 77,
		 .tx = 64,
		 .ty = 1728,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [75] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 60 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97b00000U,
			 .adv1 = 54784,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 78,
		 .tx = 64,
		 .ty = 856,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [76] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 61 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97c00000U,
			 .adv1 = 121280,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 80,
		 .tx = 64,
		 .ty = 1895,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [77] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 62 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97d00000U,
			 .adv1 = 98304,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 0,
		 .tx = 64,
		 .ty = 1536,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
	 [78] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 63 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97e00000U,
			 .adv1 = 108032,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 81,
		 .tx = 64,
		 .ty = 1688,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [79] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 64 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x97f00000U,
			 .adv1 = 88960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 85,
		 .tx = 64,
		 .ty = 1390,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [80] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x8c0U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 65 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96500000U,
			 .adv1 = 104960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 50,
		 .tx = 64,
		 .ty = 1640,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE1,
		 .desc_reload_enable = 1,
	 },
	 [81] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x40800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 66 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96600000U,
			 .adv1 = 104960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 51,
		 .tx = 64,
		 .ty = 1640,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE2,
		 .desc_reload_enable = 1,
	 },
	 [82] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0x80800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 67 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x96700000U,
			 .adv1 = 104960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 52,
		 .tx = 64,
		 .ty = 1640,
	.trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE3,
		 .desc_reload_enable = 1,
	 },
	 [83] = {
		 .src = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VMEM,
			 .line_pitch = 64,
			 .offset = 0xc0800U,
		 },
		 .dst = {
			 .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_DRAM,
			 .line_pitch = 64,
			 .slot = 68 | PVA_DMA_DYNAMIC_SLOT,
			 .offset = 0x98000000U,
			 .adv1 = 104960,
			 .rpt1 = 0,
		 },
		 .link_desc_id = 79,
		 .tx = 64,
		 .ty = 1640,
		 .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_TILE,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_WRITE4,
		 .desc_reload_enable = 1,
	 },
	 [94] = {
		 .src = {
		  .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_VPUCFG,
			 .offset = 0x80U,
		 },
		 .dst = {
		  .transfer_mode = (uint8_t)PVA_DMA_TRANS_MODE_MMIO,
		 },
		 .link_desc_id = 96,
		  .trig_event_mode = (uint8_t)PVA_DMA_TRIG_MODE_DIS,
		  .trig_vpu_events = (uint8_t)PVA_DMA_TRIG_VPU_CFG,
		 .desc_reload_enable = 1,
		 .trigger_completion = 1,
	 },
 };

static struct pva_dma_channel pfsd_dma_chs_t26x[13] = {
	 [0] = {
		 .desc_index = 0,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .output_enable_mask = 4,
	 },
	 [1] = {
		 .desc_index = 1,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .output_enable_mask = 16,
	 },
	 [2] = {
		 .desc_index = 2,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .output_enable_mask = 64,
	 },
	 [3] = {
		 .desc_index = 3,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .adb_offset = 64,
		 .output_enable_mask = 4,
	 },
	 [4] = {
		 .desc_index = 4,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .adb_offset = 64,
		 .output_enable_mask = 16,
	 },
	 [5] = {
		 .desc_index = 5,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .adb_offset = 64,
		 .output_enable_mask = 64,
	 },
	 [6] = {
		 .desc_index = 6,
		 .vdb_count = 127,
		 .output_enable_mask = 8,
	 },
	 [7] = {
		 .desc_index = 7,
		 .vdb_count = 127,
		 .output_enable_mask = 32,
	 },
	 [8] = {
		 .desc_index = 8,
		 .vdb_count = 127,
		 .output_enable_mask = 128,
	 },
	 [9] = {
		 .desc_index = 43,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .output_enable_mask = 256,
	 },
	 [10] = {
		 .desc_index = 44,
		 .prefetch_enable = 1,
		 .adb_count = 64,
		 .adb_offset = 64,
		 .output_enable_mask = 1024,
	 },
	 [11] = {
		 .desc_index = 64,
		 .prefetch_enable = 1,
		 .vdb_count = 127,
		 .output_enable_mask = 512,
	 },
	 [12] = {
		 .desc_index = 94,
		 .prefetch_enable = 1,
		 .vdb_count = 1,
		 .vdb_offset = 127,
		 .output_enable_mask = 16384,
	 },
 };

const struct pva_dma_config pfsd_dma_cfg_t26x = {
	 .header = {
		 .base_channel = 1,
		 .base_descriptor = 1,
		 .num_channels = 13,
		 .num_descriptors = 95,
		 .num_static_slots = 8,
		 .num_dynamic_slots = 69,
		 .vpu_exec_resource_id = 0,
	 },
	 .channels = pfsd_dma_chs_t26x,
	 .descriptors = pfsd_dma_descs_t26x,
	 .static_bindings = pfsd_dma_slot_buffers_t26x,
 };
