# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2025, NVIDIA CORPORATION.  All rights reserved.

obj-m += cpuidle-tegra-auto.o
obj-m += cpuidle-debugfs.o

CFLAGS_cpuidle-debugfs.o := -I$(src)
