# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

#
# Makefile sample KMD that uses IVC to communicate with a sample multi-threaded server.
ccflags-y += -Werror
ccflags-y += -Wall
obj-m     += tegra_hv_sysfs_sample_server.o
