# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.

obj-m += nnt_driver.o
nnt_driver-objs += nnt_device.o nnt_dma.o nnt_pci_conf_access.o nnt_pci_conf_access_no_vsec.o \
                   nnt_memory_access.o nnt_ioctl.o
