# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += maxim_gmsl_dp_serializer.o
obj-m += maxim_gmsl_hdmi_serializer.o
obj-m += ti_fpdlink_dp_serializer.o
obj-m += nvdisp_serdes.o

