# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# DO NOT DELETE/EDIT FILE
# Dummy Makefile needed to bypass internal pinctrl source build
