# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += ep92hx_earc.o
ep92hx_earc-objs := ep92hx.o ep92hx_isp.o
