# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

GCOV_PROFILE := y

obj-m	+= isc_gpio.o
obj-m	+= isc_mgr.o
obj-m	+= isc_dev.o
obj-m	+= isc_pwm.o
