# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

#
# Makefile for NvSciIpc driver
#

ccflags-y += -I$(PWD)

obj-m += nvsciipc.o
