/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */

#define HOST1X_COMMON_VIC_MLOCK			0x4060

#define HOST1X_COMMON_INTR_CPU0_MASK		0x4
#define HOST1X_COMMON_THOST_INTRSTATUS		0x1c
#define HOST1X_COMMON_THOST_INTRMASK		0x30
#define HOST1X_COMMON_THOST_GLOBAL_INTRMASK	0x44

#define HOST1X_COMMON_THOST_INTRMASK_VIC_ACTMON(v)		(v << 2)

#define HOST1X_COMMON_THOST_INTRSTATUS_VIC_ACTMON_INTR		BIT(2)
