# Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# The UUID for the luks-srv TA
BINARY=b83d14a8-7128-49df-9624-35f14f65ca6c

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
