# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

# The UUID for the ftpm-helper TA
BINARY=a6a3a74a-77cb-433a-990c-1dfb8a3fbc4c

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
