# SPDX-License-Identifier: GPL-2.0
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += pinctrl-tegra194-pexclk-padctrl.o
obj-m += pinctrl-tegra234-dpaux.o
obj-m += pinctrl-max77851.o
obj-m += tegra/
