################################### tell Emacs this is a -*- makefile-gmake -*-
#
# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
###############################################################################

obj-m := pva_kmd_linux.o

pva_kmd_linux-objs += ${PVA_KMD_LINUX_SRC}

ccflags-y += ${PVA_KMD_LINUX_INC}
ccflags-y += ${PVA_KMD_LINUX_DEF}
ccflags-y += ${PVA_KMD_LINUX_CFLAGS}
ccflags-y += -std=gnu11
