# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

obj-m := pva_kmd_linux.o

pva_kmd_linux-objs += ${PVA_KMD_LINUX_SRC}

ccflags-y += ${PVA_KMD_LINUX_INC}
ccflags-y += ${PVA_KMD_LINUX_DEF}
ccflags-y += ${PVA_KMD_LINUX_CFLAGS}
ccflags-y += -std=gnu11
