#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Usage: ./bmcflashqspi.sh
# This script flashes the IGX host (tegra) from BMC through the tegra's usb device interface
# using the images generated by tools/bmc_flash/l4t_generate_igx_qspi_for_bmcflash.sh

# Re-direct the tegra usb device connection from external port to BMC
gpioset -m exit gpiochip0 4=0
sleep 1

# Put the tegra in recovery mode
powerctrl recovery

if lsusb | grep -q "0955:7026"; then
    echo "Device 0955:7026 is found in lsusb output."
else
    # retry with Orin/Thor reset
    powerctrl reset
    sleep 1
    powerctrl recovery

    if lsusb | grep -q "0955:7026"; then
        echo "Device 0955:7026 is found in lsusb output."
    else
        # retry with Orin/Thor power cycle
        powerctrl power_cycle

        gpioset -m exit gpiochip0 4=0
        sleep 1

        powerctrl recovery
    fi
fi
#
#flash the igx qspi flash
#
pushd /run/initramfs/bmcflash || exit
bash ./rcmbootcmd.txt
echo "Waiting for 6 minutes before reboot the IGX......."
sleep 360

# Re-direct the tegra usb device connection to external port from BMC
gpioset -m exit gpiochip0 4=1

# reboot the Thor/Orin
powerctrl reset

popd || exit
